### ISSUE TITLE
withdraw 함수 수정 요청

### ISSUE THREAD

**Issue by SeonHwan-Kim** [ssuperpower-developer/GitPracticeProject#14]
* 혹시 잔액부족 출력을 withdrawhandle에서 하고 balance < money 일 경우 return -1;을 해주고 그 외에 return money를 하도록 수정해주실 수 있을까요?
* 아니면 return money; 대신 return balance; 로 수정 가능할까요? 
* 제가 못 찾는 걸지도 모르겠지만 withdraw 함수를 사용할 때 balance < money 인지 balance > money인지 구분이 안되는 것 같습니다...

_Originally posted by @SeonHwan-Kim in https://github.com/ssuperpower-developer/GitPracticeProject/pull/12#discussion_r927865162_

**Comment by 0zlrlo** [comment]
함수 수정은 완료하였는데 push할 때에 문제가 생겨, 해결하고 바로 올리도록 하겠습니다.

**Comment by jwchoi179** [comment]
오 여기서 잘 소통하고 문제가 해결된다면 코멘트를 닫으시면 됩니다!
